In [1]:
import pandas as pd

In [13]:
# características de los datos
df1 = pd.read_csv('Conjunto_datos_BASICO_AgroCebada2026.csv')
df2 = pd.read_csv('Conjunto_datos_PRO_AgroCebada.csv')
# variable objetivo

y = pd.read_csv('ID_area_rendimiento_70_30_Reto_AgroCebada.csv' )

In [4]:
df1.head()

,ID_POLIGONO,fecha_captura,sensor,ndvi_promedio,ndvi_std,ndvi_max,ndvi_min,evi_promedio,evi_std,evi_max,...,dswi5_min,nddi_promedio,nddi_std,nddi_max,nddi_min,enddi_promedio,enddi_std,enddi_max,enddi_min,porcentaje_nubosidad
0,AGC_011,20/04/2022,Landsat,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
1,AGC_011,16/03/2024,Landsat,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
2,AGC_011,15/03/2024,Landsat,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
3,AGC_011,26/08/2025,Landsat,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
4,AGC_011,10/03/2025,Landsat,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0

In [5]:
df1.describe()

,ndvi_promedio,ndvi_std,ndvi_max,ndvi_min,evi_promedio,evi_std,evi_max,evi_min,crc_promedio,crc_std,...,dswi5_min,nddi_promedio,nddi_std,nddi_max,nddi_min,enddi_promedio,enddi_std,enddi_max,enddi_min,porcentaje_nubosidad
count,44877.000000,44877.000000,44877.000000,44877.000000,44877.000000,44877.000000,44877.000000,44877.000000,44877.000000,44877.000000,...,44877.000000,44877.000000,44877.000000,44877.000000,44877.000000,44877.000000,44877.000000,44877.000000,44877.000000,104610.000000
mean,0.242993,0.046832,0.414484,0.140941,0.190303,0.042548,0.353817,0.103929,0.346804,0.038928,...,0.767356,0.073527,0.021189,0.139107,0.008892,0.136345,0.020775,0.204825,0.075231,32.252534
std,0.157198,0.030247,0.192034,0.098607,0.142251,0.034267,0.208074,0.077956,0.127820,0.036832,...,0.164361,0.052217,0.010963,0.057327,0.056376,0.042674,0.010545,0.050712,0.050437,45.089854
min,-0.066000,0.002000,0.002000,-0.110000,-0.031000,0.002000,0.000000,-0.921000,-0.700000,0.001000,...,0.334000,-0.288000,0.001000,-0.262000,-0.304000,-0.255000,0.001000,-0.238000,-0.271000,0.000000
25%,0.138000,0.023000,0.252000,0.091000,0.103000,0.018000,0.199000,0.064000,0.328000,0.020000,...,0.666000,0.040000,0.014000,0.105000,-0.020000,0.118000,0.014000,0.179000,0.055000,0.000000
50%,0.175000,0.041000,0.379000,0.115000,0.130000,0.032000,0.286000,0.084000,0.386000,0.027000,...,0.710000,0.079000,0.019000,0.144000,0.014000,0.142000,0.019000,0.207000,0.084000,0.000000
75%,0.299000,0.063000,0.556000,0.171000,0.219000,0.056000,0.451000,0.123000,0.420000,0.041000,...,0.818000,0.111000,0.026000,0.175000,0.047000,0.163000,0.025000,0.234000,0.108000,100.000000
max,0.820000,0.258000,0.890000,0.685000,0.905000,0.317000,1.000000,0.758000,0.561000,0.389000,...,1.913000,0.277000,0.159000,0.534000,0.177000,0.308000,0.148000,0.515000,0.206000,100.000000

In [7]:
df1.info()

<class 'pandas.DataFrame'>
RangeIndex: 107666 entries, 0 to 107665
Data columns (total 96 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   ID_POLIGONO           107666 non-null  str
 1   fecha_captura         107666 non-null  str
 2   sensor                107666 non-null  str
 3   ndvi_promedio         44877 non-null   float64
 4   ndvi_std              44877 non-null   float64
 5   ndvi_max              44877 non-null   float64
 6   ndvi_min              44877 non-null   float64
 7   evi_promedio          44877 non-null   float64
 8   evi_std               44877 non-null   float64
 9   evi_max               44877 non-null   float64
 10  evi_min               44877 non-null   float64
 11  crc_promedio          44877 non-null   float64
 12  crc_std               44877 non-null   float64
 13  crc_max               44877 non-null   float64
 14  crc_min               44877 non-null   float64
 15  mcrc_promedio         44877 non-null   float64
 16  mcrc_std              44877 non-null   float64
 17  mcrc_max              44877 non-null   float64
 18  mcrc_min              44877 non-null   float64
 19  ndsvi_promedio        44877 non-null   float64
 20  ndsvi_std             44877 non-null   float64
 21  ndsvi_max             44877 non-null   float64
 22  ndsvi_min             44877 non-null   float64
 23  srndi_promedio        44877 non-null   float64
 24  srndi_std             44877 non-null   float64
 25  srndi_max             44877 non-null   float64
 26  srndi_min             44877 non-null   float64
 27  mra_promedio          44877 non-null   float64
 28  mra_std               44877 non-null   float64
 29  mra_max               44877 non-null   float64
 30  mra_min               44877 non-null   float64
 31  lai_promedio          44877 non-null   float64
 32  lai_std               44877 non-null   float64
 33  lai_max               44877 non-null   float64
 34  lai_min               44877 non-null   float64
 35  fapar_promedio        44873 non-null   float64
 36  fapar_std             44873 non-null   float64
 37  fapar_max             44873 non-null   float64
 38  fapar_min             44873 non-null   float64
 39  savi_promedio         44877 non-null   float64
 40  savi_std              44877 non-null   float64
 41  savi_max              44877 non-null   float64
 42  savi_min              44877 non-null   float64
 43  vi6t_promedio         31048 non-null   float64
 44  vi6t_std              31048 non-null   float64
 45  vi6t_max              31048 non-null   float64
 46  vi6t_min              31048 non-null   float64
 47  ndti_promedio         44877 non-null   float64
 48  ndti_std              44877 non-null   float64
 49  ndti_max              44877 non-null   float64
 50  ndti_min              44877 non-null   float64
 51  sti_promedio          44877 non-null   float64
 52  sti_std               44877 non-null   float64
 53  sti_max               44877 non-null   float64
 54  sti_min               44877 non-null   float64
 55  ndwi_promedio         44877 non-null   float64
 56  ndwi_std              44877 non-null   float64
 57  ndwi_max              44877 non-null   float64
 58  ndwi_min              44877 non-null   float64
 59  endwi_promedio        44877 non-null   float64
 60  endwi_std             44877 non-null   float64
 61  endwi_max             44877 non-null   float64
 62  endwi_min             44877 non-null   float64
 63  msi_promedio          44877 non-null   float64
 64  msi_std               44877 non-null   float64
 65  msi_max               44877 non-null   float64
 66  msi_min               44877 non-null   float64
 67  emsi_promedio         44877 non-null   float64
 68  emsi_std              44877 non-null   float64
 69  emsi_max              44877 non-null   float64
 70  emsi_min              44877 non-null   float64
 71  dswi2_promedio        44877 non-null   float64
 72  dswi2_std             44877 non-null   float64
 73  dswi2_max             44877 non-null   float64
 74  dswi2_min             44877 non-null   float64
 75  dswi3_promedio        44877 non-null   float64
 76  dswi3_std             44877 non-null   float64
 77  dswi3_max             44877 non-null   float64
 78  dswi3_min             44877 non-null   float64
 79  dswi4_promedio        44877 non-null   float64
 80  dswi4_std             44877 non-null   float64
 81  dswi4_max             44877 non-null   float64
 82  dswi4_min             44877 non-null   float64
 83  dswi5_promedio        44877 non-null   float64
 84  dswi5_std             44877 non-null   float64
 85  dswi5_max             44877 non-null   float64
 86  dswi5_min             44877 non-null   float64
 87  nddi_promedio         44877 non-null   float64
 88  nddi_std              44877 non-null   float64
 89  nddi_max              44877 non-null   float64
 90  nddi_min              44877 non-null   float64
 91  enddi_promedio        44877 non-null   float64
 92  enddi_std             44877 non-null   float64
 93  enddi_max             44877 non-null   float64
 94  enddi_min             44877 non-null   float64
 95  porcentaje_nubosidad  104610 non-null  float64
dtypes: float64(93), str(3)
memory usage: 81.5 MB

In [8]:
df1.isna().sum()

ID_POLIGONO                 0
fecha_captura               0
sensor                      0
ndvi_promedio           62789
ndvi_std                62789
                        ...
enddi_promedio          62789
enddi_std               62789
enddi_max               62789
enddi_min               62789
porcentaje_nubosidad     3056
Length: 96, dtype: int64

In [9]:
df2.head()

,ID_POLIGONO,fecha_captura,sensor,ndvi_promedio,ndvi_std,ndvi_max,ndvi_min,evi_promedio,evi_std,evi_max,evi_min,lai_promedio,lai_std,lai_max,lai_min,msavi_promedio,msavi_std,msavi_max,msavi_min,porcentaje_nubosidad
0,AGC_056,05/02/2025,Planet,0.300,0.042,0.553,0.175,0.138,0.022,0.251,0.068,1.049,0.182,2.144,0.586,0.135,0.022,0.244,0.066,0.0
1,AGC_056,08/02/2025,Planet,0.204,0.043,0.529,0.125,0.110,0.018,0.209,0.074,0.697,0.167,1.888,0.247,0.110,0.018,0.207,0.072,0.0
2,AGC_056,07/02/2025,Planet,0.241,0.043,0.534,0.154,0.134,0.018,0.224,0.098,0.826,0.159,1.858,0.404,0.135,0.018,0.230,0.098,0.0
3,AGC_056,09/02/2025,Planet,0.246,0.039,0.536,0.153,0.142,0.018,0.243,0.098,0.818,0.159,1.849,0.399,0.141,0.018,0.237,0.095,0.0
4,AGC_056,30/01/2025,Planet,0.211,0.046,0.533,0.113,0.110,0.020,0.229,0.069,0.724,0.187,1.955,0.277,0.111,0.021,0.230,0.067,0.0

In [10]:
df2.describe()

,ndvi_promedio,ndvi_std,ndvi_max,ndvi_min,evi_promedio,evi_std,evi_max,evi_min,lai_promedio,lai_std,lai_max,lai_min,msavi_promedio,msavi_std,msavi_max,msavi_min,porcentaje_nubosidad
count,35747.000000,35747.000000,35747.000000,35747.000000,35747.000000,35747.000000,35747.000000,35747.000000,35747.000000,35747.000000,35747.000000,35747.000000,35747.000000,35747.000000,35747.000000,35747.000000,47804.000000
mean,0.353691,0.048364,0.542829,0.222416,0.214637,0.034301,0.352087,0.129989,1.215302,0.186328,1.967385,0.700876,0.211447,0.034429,0.347286,0.126785,30.102702
std,0.174964,0.028342,0.185630,0.126998,0.123494,0.026199,0.163932,0.080384,0.612512,0.099909,0.683241,0.493474,0.122765,0.027021,0.163722,0.077320,44.208162
min,0.007000,0.008000,0.032000,-0.585000,0.028000,0.006000,0.067000,-0.916000,-0.112000,0.021000,-0.040000,-0.200000,0.010000,0.005000,0.042000,-0.649000,0.000000
25%,0.227000,0.027000,0.386000,0.142000,0.133000,0.016000,0.229000,0.082000,0.785000,0.113000,1.397000,0.366000,0.129000,0.016000,0.224000,0.080000,0.000000
50%,0.275000,0.043000,0.511000,0.186000,0.160000,0.025000,0.293000,0.106000,0.962000,0.162000,1.822000,0.565000,0.157000,0.025000,0.288000,0.104000,0.000000
75%,0.451000,0.063000,0.704000,0.270000,0.252000,0.044000,0.450000,0.155000,1.499000,0.232000,2.494000,0.920000,0.251000,0.044000,0.446000,0.154000,100.000000
max,0.907000,0.251000,0.999000,0.746000,0.877000,0.269000,1.000000,0.610000,3.663000,0.870000,4.428000,2.829000,0.780000,0.248000,0.917000,0.574000,100.000000

In [11]:
df2.info()

<class 'pandas.DataFrame'>
RangeIndex: 47804 entries, 0 to 47803
Data columns (total 20 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   ID_POLIGONO           47804 non-null  str
 1   fecha_captura         47804 non-null  str
 2   sensor                47804 non-null  str
 3   ndvi_promedio         35747 non-null  float64
 4   ndvi_std              35747 non-null  float64
 5   ndvi_max              35747 non-null  float64
 6   ndvi_min              35747 non-null  float64
 7   evi_promedio          35747 non-null  float64
 8   evi_std               35747 non-null  float64
 9   evi_max               35747 non-null  float64
 10  evi_min               35747 non-null  float64
 11  lai_promedio          35747 non-null  float64
 12  lai_std               35747 non-null  float64
 13  lai_max               35747 non-null  float64
 14  lai_min               35747 non-null  float64
 15  msavi_promedio        35747 non-null  float64
 16  msavi_std             35747 non-null  float64
 17  msavi_max             35747 non-null  float64
 18  msavi_min             35747 non-null  float64
 19  porcentaje_nubosidad  47804 non-null  float64
dtypes: float64(17), str(3)
memory usage: 8.3 MB

In [12]:
df2.isna().sum()

ID_POLIGONO                 0
fecha_captura               0
sensor                      0
ndvi_promedio           12057
ndvi_std                12057
ndvi_max                12057
ndvi_min                12057
evi_promedio            12057
evi_std                 12057
evi_max                 12057
evi_min                 12057
lai_promedio            12057
lai_std                 12057
lai_max                 12057
lai_min                 12057
msavi_promedio          12057
msavi_std               12057
msavi_max               12057
msavi_min               12057
porcentaje_nubosidad        0
dtype: int64

In [14]:
y.head()

  ID_POLIGONO  AREA_HA  RENDIMIENTO_T_HA       CONJUNTO  Unnamed: 4
0     AGC_001     7.61              3.50  ENTRENAMIENTO         NaN
1     AGC_002     2.31              4.63  ENTRENAMIENTO         NaN
2     AGC_003    18.68               NaN     PREDICCION         NaN
3     AGC_004     8.00              3.00  ENTRENAMIENTO         NaN
4     AGC_005     2.27              5.16  ENTRENAMIENTO         NaN

In [15]:
y.describe()

          AREA_HA  RENDIMIENTO_T_HA  Unnamed: 4
count  197.000000        138.000000         0.0
mean     6.604315          3.955362         NaN
std      7.437631          0.851161         NaN
min      0.350000          2.000000         NaN
25%      2.300000          3.200000         NaN
50%      5.460000          4.340000         NaN
75%      8.090000          4.550000         NaN
max     64.300000          5.590000         NaN

In [17]:
y.columns

Index(['ID_POLIGONO', 'AREA_HA', 'RENDIMIENTO_T_HA', 'CONJUNTO', 'Unnamed: 4'], dtype='str')

In [19]:
y.info()

<class 'pandas.DataFrame'>
RangeIndex: 197 entries, 0 to 196
Data columns (total 5 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   ID_POLIGONO       197 non-null    str
 1   AREA_HA           197 non-null    float64
 2   RENDIMIENTO_T_HA  138 non-null    float64
 3   CONJUNTO          197 non-null    str
 4   Unnamed: 4        0 non-null      float64
dtypes: float64(3), str(2)
memory usage: 11.5 KB